name: bbmstu_app
description: BITOP Bauman App
version: 4.4.25+117
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  firebase_analytics: ^8.3.1
  firebase_core: ^1.6.0
  firebase_messaging: ^11.1.0
  firebase_remote_config: ^0.11.0+2
  firebase_crashlytics: ^2.3.0
  cloud_firestore: ^3.1.0
  rxdart: ^0.27.2
  url_launcher: ^6.0.13
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.1.0
  flutter_markdown: ^0.6.6
  intl: ^0.17.0
  # State management
  flutter_bloc: ^7.3.0
  # Old state management
  hooks_riverpod: ^0.14.0+4
  flutter_hooks: ^0.17.0
  # Value equality
  equatable: ^2.0.3
  # Local cache
  shared_preferences: ^2.0.7
  # check network connection
  internet_connection_checker: ^0.0.1+2
  # For custom text overflow
  extended_text: ^9.0.0
  # WebView for login
  webview_flutter: ^2.3.1
  timezone: ^0.8.0
  freezed: ^0.14.2
  json_annotation: ^4.3.0
  qr_flutter: ^4.0.0
  image_picker: ^0.8.4+4
  chopper: ^4.0.1
  uuid: ^3.0.5
  permission_handler: ^8.2.6
  app_settings: ^4.1.1
  sealed_unions: ^3.0.3+1
  dartz: ^0.10.0

  local_database:
    path: packages/local_database
  remote_api:
    path: packages/remote_api
  screen_brightness: ^0.1.1
  charcode: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.0.1
  dart_code_metrics: ^4.9.1
  pubspec_generator: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - packages/timezone/data/2021a.tzf

  fonts:
    - family: StandardIcons
      fonts:
        - asset: assets/fonts/standard_icons.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-BlackItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-BoldItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Italic.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
        - asset: assets/fonts/roboto/Roboto-LightItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-MediumItalic.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
        - asset: assets/fonts/roboto/Roboto-ThinItalic.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
