targets:
  $default:
    sources:
      - swagger/**
      - lib/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'swagger/'
          output_folder: 'lib/src/swagger_generated_code/'
          build_only_models: true
          default_values_map:
            - type_name: int
              default_value: '0'
            - type_name: String
              default_value: ''
            - type_name: bool
              default_value: 'false'
            - type_name: List
              default_value: '[]'