name: remote_api
description: Remote API.
version: 1.0.2
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  chopper: ^4.0.1

dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  chopper_generator: ^4.0.5
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  swagger_dart_code_generator: ^2.4.1